from sage.all import (
    GF, PolynomialRing, identity_matrix, is_prime_power, matrix, random_matrix, span,
    vector,
)
from sage.all import randint, random

from lincodes import _check_code, Dual, Hull, Dehull
import util


def SampleLCD(n, k, q, chi):
    """
    [Figure 14]

    Outputs a uniformly random [n,k]-linear LCD code over FF_q with square class chi.
    """
    assert k >= 0 and k <= n // 2
    assert is_prime_power(q)
    assert chi == 1 or chi == -1
    if k == 0:
        return matrix(GF(q), 0, n)
    for _ in range(k):
        A = random_matrix(GF(q), k, n)
        if A.rank() != k:  # not full-rank
            continue
        G = A * A.T
        if G.rank() != k:  # not LCD
            continue
        chiA = 1 if G.det().is_square() else -1
        if chi != chiA:  # not correct genus
            continue
        return A
    return None


def FindPlane(A, i_=0, j_=1):
    """
    [Figure 15]

    Given a h-hollow A with k-h >= 2, output a matrix spanning the same code as A with
    rows i_ and j_ spanning a regular plane.
    """
    n, k, F = _check_code(A)
    G = A * A.T
    assert G.rank() >= 2
    assert i_ != j_
    assert i_ >= 0 and i_ < k and j_ >= 0 and j_ < k
    for i in range(k):
        if G[i][i] == 0:
            continue
        # else G[i][i] != 0:
        rows = A.rows()
        rows[0], rows[i] = rows[i], rows[0]
        for j in range(1, k):
            rows[j] = rows[j] - (rows[0] * rows[j]) / (rows[0] * rows[0]) * rows[0]
        A_ = matrix(rows[1:])
        G_ = A_ * A_.T
        for j in range(k-1):
            if G_[j][j] == 0:
                continue
            # else G_[j][j] != 0:
            util._swap_pairs(rows, 0, j+1, i_, j_)
            B = matrix(rows)
            assert util._disc(B[i_], B[j_]) != 0
            assert span(A) == span(B)
            return B
        # else G_[j][j] = 0 for all j:
        for ii in range(k-1):
            for jj in range(ii+1, k-1):
                if G_[ii][jj] != 0:  # always true for at least one pair (ii,jj)
                    util._swap_pairs(rows, ii+1, jj+1, i_, j_)
                    B = matrix(rows)
                    assert util._disc(B[i_], B[j_]) != 0
                    assert span(A) == span(B)
                    return B
    # else G[i][i] = 0 for all i:
    for ii in range(k):
        for jj in range(ii+1, k):
            if G[ii][jj] != 0:  # always true for at least one pair (ii,jj)
                rows = A.rows()
                util._swap_pairs(rows, ii, jj, i_, j_)
                B = matrix(rows)
                assert util._disc(B[i_], B[j_]) != 0
                assert span(A) == span(B)
                return B


def FindPlaneH(A, i_=0, j_=1):
    """
    [Figure 15]

    Given a h-hollow A with k-h >= 2, output a matrix spanning the same code as A with
    rows i_ and j_ spanning a hyperbolic plane, or abort if anisotropic.
    """
    assert i_ != j_
    T, H = Dehull(A)
    n, k, F = _check_code(T)
    assert k >= 2
    if k == 2 and (T * T.T).det().is_square() != F(-1).is_square():
        return None  # anisotropic case
    A_ = FindPlane(T, k-2, k-1)
    B = A_[k-2:]
    # are we lucky and have a hyperbolic plane already?
    if (B * B.T).det().is_square() == F(-1).is_square():
        M = A_.stack(H)
        util._swap_pairs(M, k-2, k-1, i_, j_)
        return M
    # otherwise, construct *any* non-hull self-orthogonal vector
    v, c = None, None
    R, X = PolynomialRing(F, "X").objgen()
    pre_x = [util.random_invertible(len(F)) for i in range(k-2)]
    for a in F:
        x = vector(R, pre_x + [a, X])
        poly = x * A_ * A_.T * x
        if poly == 0:
            c = vector(F, pre_x + [a, F(1)])
        else:
            rs = poly.roots(multiplicities=False)
            if not rs:
                continue
            c = vector(F, pre_x + [a, rs[0]])
        v = c * A_
        break
    assert c is not None and v is not None  # this cannot happen if q odd
    # make a hyperbolic pair
    y = matrix(c * A_ * A_.T).solve_right(vector(F, [1]))
    z = y - (y * A_ * A_.T * y) * F(2).inverse() * c
    w = z * A_
    assert v * v == 0 and w * w == 0 and v * w == 1
    # compute a basis that starts with v and w
    rows = [v, w]
    T_ = matrix(F, rows)
    for r in A_:
        if T_.rank() < T_.stack(matrix(r)).rank():
            T_ = T_.stack(matrix(r))
    M = T_.stack(H)
    util._swap_pairs(M, 0, 1, i_, j_)
    return M


def SampleSelfOrthogonal(A, n=None, q=None):
    """
    [Figure 16] as SSO

    Sample a uniformly random self-orthogonal vector from a code generated by A.
    To sample a self-orthogonal vector from FF_q^n, run with ([], n=n, q=q).
    """
    # return a random s.o. vector if A is empty
    if not A:
        if n is None or q is None:
            return None
        assert n > 0
        assert is_prime_power(q)
        A = identity_matrix(GF(q), n)
    n, k, F = _check_code(A)
    q = len(F)

    # G = FindPlane(A, k-2, k-1)
    G = FindPlaneH(A, k-2, k-1)
    if G is None:  # anisotropic case, return hull vector
        H = Hull(A)
        if H.nrows() == 0:
            return vector(F, [0] * n)
        c = vector(F, [F.random_element() for _ in range(H.nrows())])
        return c * H
    D = util._disc(G[k-2], G[k-1])
    assert (-D).is_square() == F(-1).is_square()
    M = util._maxsols(D, F)
    assert M == 2 * q - 1
    halt = n * (q+1)

    R, X = PolynomialRing(F, "X").objgen()
    for i in range(halt):
        pre_x = [F.random_element() for i in range(k-2)]
        roots = []
        for a in F:
            x = vector(R, pre_x + [a, X])
            poly = x * G * G.T * x
            if poly == 0:
                for r in F:
                    roots.append((a, r))
            else:
                rs = poly.roots(multiplicities=False)
                for r in rs:
                    roots.append((a, r))
        L = len(roots)
        assert L == M or L == M-len(F)
        if random() > L / M:
            continue
        # sample random solution
        sol = list(roots[randint(0, L-1)])
        # construct so vector
        cs = vector(F, pre_x + sol)
        v = cs * G
        assert v * v == 0
        return v
    return None


def SampleCode(n, k, h, q, chi, randomize=True):
    """
    [Figure 17]

    Returns a random [n,k]-linear code over FF_q with 2*k <= n, hull dimension h <= k
    and square class chi. Chi is ignored if h = k.
    """
    assert k >= 1 and h >= 0 and h <= k and 2 * k <= n and chi in [1, -1]
    F = GF(q)
    A_0 = SampleLCD(n, k-h, q, chi)
    if A_0 is None:
        return None
    A_i = A_0
    for i in range(h):
        A_i_ = Dual(A_i)
        y = None
        for j in range(k * q):
            y = SampleSelfOrthogonal(A_i_)
            if y is None:
                continue
            if i > 0 and y in span(Hull(A_i)):
                y = None
                continue
            break
        if y is None:
            return None
        A_i = A_i.stack(matrix(F, 1, n, y))
    A_h = A_i
    assert A_h.rank() == k and (A_h * A_h.T).rank() == k - h
    # optionally randomise basis
    S = util.random_fullrank_matrix(k, len(F)) if randomize else 1
    return S * A_h


def SampleHollow(n, k, h, q):
    """
    [Figure 18]

    Sample negligibly close to uniform [n,k]-linear h-hollow codes over FF_q.
    """
    chi = 2 * util.random_bit() - 1
    return SampleCode(n, k, h, q, chi)


# misc:

def SampleSelfOrthogonalCode(n, k, q):
    """
    Return a random self-orthogonal i.e. weakly self-dual [n,k]-linear code over FF_q.
    """
    return SampleCode(n, k, k, q, 1)


def SampleSelfDualCode(n, q):
    """
    Return a random self-dual [2n,n]-linear code over FF_q.
    """
    assert q % 2 == 1
    assert q % 4 == 1 or n % 2 == 0
    return SampleSelfOrthogonalCode(2 * n, n, q)
